-- ============================================================================
-- RLS in InitPlan form — every remaining per-row auth.uid() / role-helper call
-- (01.10.2026 — after the agents' order-search timeout, 20260944000450)
-- ============================================================================
-- GENERATED by scripts/gen-rls-initplan.mjs from the live policies (pg_get_expr, search_path '').
-- Do not hand-edit: regenerate. Verify with scripts/verify-rls-initplan.mjs.
--
-- Why: a policy that calls auth.uid() or has_role(auth.uid(), …) / is_admin_or_manager(auth.uid())
-- / is_internal_staff(auth.uid()) / get_my_affiliate_id() directly is evaluated PER ROW whenever
-- the query also has a non-leakproof predicate (LIKE, ILIKE, most functions): Postgres must apply
-- the RLS quals first. On 01.10 that turned an agent's phone search on orders into ~358k
-- has_role() calls and a statement timeout. Wrapping each call in a scalar sub-select —
-- (SELECT auth.uid()), (SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) —
-- lets the planner compute it ONCE per query (an InitPlan).
--
-- WHO SEES / WRITES WHAT DOES NOT CHANGE. Only those calls are wrapped; each is STABLE and gets no
-- column of the row (auth.uid() or a constant only), so its value is the same for every row of a
-- statement. ALTER POLICY keeps the name, command, roles and permissive/restrictive; a USING or
-- WITH CHECK that needs no change is not restated. Policies already in InitPlan form (e.g. the
-- (SELECT is_business_owner(…)) ones, web_sync_runs, orders / order_items) are untouched.
--
-- Scope: 150 of the 179 policies of schema public, on 64 tables. orders / order_items excluded (done).
--
-- How it runs (node scripts/apply-migration-mk.mjs 20260944000460_rls_initplan_all.sql):
--   * ONE transaction per table with SET LOCAL lock_timeout = '5s' — ALTER POLICY needs an
--     ACCESS EXCLUSIVE lock, and the syncs write constantly. A table that stays busy for 5 s is
--     skipped (its block catches lock_not_available) so the others still go through. While the
--     ALTER waits for its lock, new reads of that table queue behind it (≤ 5 s): on user_roles
--     (read by every has_role()) and profiles that is a short app-wide pause — apply in the
--     quiet window after 20:55 Skopje.
--   * Drift guard: before altering, each policy's live expression must still be the one this file
--     was generated from (whitespace and InitPlan wrappers aside). If another session changed a
--     policy since, the run STOPS with "rls_initplan: … changed since generation" — regenerate.
--   * At the end, if any table was skipped, the run raises "rls_initplan: lock timeout on: …" so
--     apply-migration-mk does NOT record the version. Just run the same command again (best in the
--     quiet window after 20:55 Skopje): the tables already done pass the guard and are re-set to
--     the same text, harmlessly. ALTER POLICY is idempotent.
-- ============================================================================

-- session scratch (pg_temp: gone when the connection closes)
SELECT pg_catalog.set_config('elyon.rls_initplan_busy', '', false);

CREATE OR REPLACE FUNCTION pg_temp.rls_initplan_norm(e text) RETURNS text
LANGUAGE sql IMMUTABLE AS $f$
  SELECT regexp_replace(
           regexp_replace(
             regexp_replace(e, '\s+', ' ', 'g'),
             '\( ?SELECT (auth\.(uid|jwt|role)\(\))( AS [a-z_]+)?\)', '\1', 'g'),
           '\( ?SELECT (public\.[a-z_]+\((?:[^()'']|\(\)|''(?:[^'']|'''')*'')*\))( AS [a-z_]+)?\)', '\1', 'g')
$f$;

CREATE OR REPLACE FUNCTION pg_temp.rls_initplan_guard(p_table text, p_policy text, p_using text, p_check text)
RETURNS void LANGUAGE plpgsql SET search_path = '' AS $f$
DECLARE
  q text;
  w text;
BEGIN
  SELECT pg_catalog.pg_get_expr(p.polqual, p.polrelid), pg_catalog.pg_get_expr(p.polwithcheck, p.polrelid)
    INTO q, w
    FROM pg_catalog.pg_policy p
   WHERE p.polrelid = pg_catalog.to_regclass('public.' || pg_catalog.quote_ident(p_table))
     AND p.polname = p_policy;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'rls_initplan: policy "%" on public.% is gone - regenerate (node scripts/gen-rls-initplan.mjs)', p_policy, p_table;
  END IF;
  IF pg_temp.rls_initplan_norm(q) IS DISTINCT FROM pg_temp.rls_initplan_norm(p_using)
     OR pg_temp.rls_initplan_norm(w) IS DISTINCT FROM pg_temp.rls_initplan_norm(p_check) THEN
    RAISE EXCEPTION 'rls_initplan: policy "%" on public.% changed since generation - regenerate (node scripts/gen-rls-initplan.mjs)', p_policy, p_table;
  END IF;
END
$f$;

CREATE OR REPLACE FUNCTION pg_temp.rls_initplan_busy(p_table text) RETURNS void
LANGUAGE plpgsql AS $f$
BEGIN
  RAISE NOTICE 'rls_initplan: public.% busy (lock timeout) - not changed, re-run', p_table;
  PERFORM pg_catalog.set_config('elyon.rls_initplan_busy',
    pg_catalog.concat_ws(' ', NULLIF(pg_catalog.current_setting('elyon.rls_initplan_busy', true), ''), p_table), false);
END
$f$;

-- ── public.active_call_views ─────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('active_call_views', 'Agents manage own views',
    $o$(agent_id = auth.uid())$o$,
    $o$(agent_id = auth.uid())$o$);
  PERFORM pg_temp.rls_initplan_guard('active_call_views', 'Internal staff can read active views',
    $o$public.is_internal_staff(auth.uid())$o$,
    NULL);
  ALTER POLICY "Agents manage own views" ON public.active_call_views
    USING ((agent_id = (SELECT auth.uid())))
    WITH CHECK ((agent_id = (SELECT auth.uid())));
  ALTER POLICY "Internal staff can read active views" ON public.active_call_views
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('active_call_views');
END
$rls$;
COMMIT;

-- ── public.admin_login_logs ──────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('admin_login_logs', 'Admins can read admin login logs',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can read admin login logs" ON public.admin_login_logs
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('admin_login_logs');
END
$rls$;
COMMIT;

-- ── public.ads_audit_logs ────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('ads_audit_logs', 'Admins and ads admins can view audit logs',
    $o$(public.has_role(auth.uid(), 'ads_admin'::public.app_role) OR public.has_role(auth.uid(), 'admin'::public.app_role))$o$,
    NULL);
  ALTER POLICY "Admins and ads admins can view audit logs" ON public.ads_audit_logs
    USING (((SELECT public.has_role((SELECT auth.uid()), 'ads_admin'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('ads_audit_logs');
END
$rls$;
COMMIT;

-- ── public.ads_campaigns ─────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('ads_campaigns', 'Admins and ads admins can manage campaigns',
    $o$(public.has_role(auth.uid(), 'ads_admin'::public.app_role) OR public.has_role(auth.uid(), 'admin'::public.app_role))$o$,
    NULL);
  ALTER POLICY "Admins and ads admins can manage campaigns" ON public.ads_campaigns
    USING (((SELECT public.has_role((SELECT auth.uid()), 'ads_admin'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('ads_campaigns');
END
$rls$;
COMMIT;

-- ── public.affiliate_leads ───────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('affiliate_leads', 'Admins and managers manage affiliate_leads',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('affiliate_leads', 'Affiliate reads own leads',
    $o$(affiliate_id = public.get_my_affiliate_id())$o$,
    NULL);
  ALTER POLICY "Admins and managers manage affiliate_leads" ON public.affiliate_leads
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
  ALTER POLICY "Affiliate reads own leads" ON public.affiliate_leads
    USING ((affiliate_id = (SELECT public.get_my_affiliate_id())));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('affiliate_leads');
END
$rls$;
COMMIT;

-- ── public.affiliate_offers ──────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('affiliate_offers', 'Admins and managers manage affiliate_offers',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('affiliate_offers', 'Affiliate reads own approvals',
    $o$(affiliate_id = public.get_my_affiliate_id())$o$,
    NULL);
  ALTER POLICY "Admins and managers manage affiliate_offers" ON public.affiliate_offers
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
  ALTER POLICY "Affiliate reads own approvals" ON public.affiliate_offers
    USING ((affiliate_id = (SELECT public.get_my_affiliate_id())));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('affiliate_offers');
END
$rls$;
COMMIT;

-- ── public.affiliates ────────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('affiliates', 'Admins and managers manage affiliates',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('affiliates', 'Affiliate reads own row',
    $o$(user_id = auth.uid())$o$,
    NULL);
  ALTER POLICY "Admins and managers manage affiliates" ON public.affiliates
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
  ALTER POLICY "Affiliate reads own row" ON public.affiliates
    USING ((user_id = (SELECT auth.uid())));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('affiliates');
END
$rls$;
COMMIT;

-- ── public.agent_payout_items ────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('agent_payout_items', 'Admins/managers read agent_payout_items',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('agent_payout_items', 'Agents read own agent_payout_items',
    $o$(EXISTS ( SELECT 1
   FROM public.agent_payouts p
  WHERE ((p.id = agent_payout_items.payout_id) AND (p.agent_user_id = auth.uid()))))$o$,
    NULL);
  ALTER POLICY "Admins/managers read agent_payout_items" ON public.agent_payout_items
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
  ALTER POLICY "Agents read own agent_payout_items" ON public.agent_payout_items
    USING ((EXISTS ( SELECT 1
   FROM public.agent_payouts p
  WHERE ((p.id = agent_payout_items.payout_id) AND (p.agent_user_id = (SELECT auth.uid()))))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('agent_payout_items');
END
$rls$;
COMMIT;

-- ── public.agent_payouts ─────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('agent_payouts', 'Admins/managers read agent_payouts',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('agent_payouts', 'Agents read own agent_payouts',
    $o$(agent_user_id = auth.uid())$o$,
    NULL);
  ALTER POLICY "Admins/managers read agent_payouts" ON public.agent_payouts
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
  ALTER POLICY "Agents read own agent_payouts" ON public.agent_payouts
    USING ((agent_user_id = (SELECT auth.uid())));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('agent_payouts');
END
$rls$;
COMMIT;

-- ── public.altercpa_accounts ─────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('altercpa_accounts', 'Admins and managers manage altercpa accounts',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    NULL);
  ALTER POLICY "Admins and managers manage altercpa accounts" ON public.altercpa_accounts
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('altercpa_accounts');
END
$rls$;
COMMIT;

-- ── public.altercpa_leads ────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('altercpa_leads', 'Admins and managers read altercpa leads',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    NULL);
  ALTER POLICY "Admins and managers read altercpa leads" ON public.altercpa_leads
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('altercpa_leads');
END
$rls$;
COMMIT;

-- ── public.altercpa_offer_map ────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('altercpa_offer_map', 'Admins and managers manage altercpa offer map',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    NULL);
  ALTER POLICY "Admins and managers manage altercpa offer map" ON public.altercpa_offer_map
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('altercpa_offer_map');
END
$rls$;
COMMIT;

-- ── public.altercpa_sync_runs ────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('altercpa_sync_runs', 'Admins and managers read altercpa sync runs',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    NULL);
  ALTER POLICY "Admins and managers read altercpa sync runs" ON public.altercpa_sync_runs
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('altercpa_sync_runs');
END
$rls$;
COMMIT;

-- ── public.altercpa_webmasters ───────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('altercpa_webmasters', 'Admins and managers manage altercpa webmasters',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    NULL);
  ALTER POLICY "Admins and managers manage altercpa webmasters" ON public.altercpa_webmasters
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('altercpa_webmasters');
END
$rls$;
COMMIT;

-- ── public.app_settings ──────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('app_settings', 'Admins can manage app_settings',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$);
  PERFORM pg_temp.rls_initplan_guard('app_settings', 'Internal staff can read app_settings',
    $o$public.is_internal_staff(auth.uid())$o$,
    NULL);
  ALTER POLICY "Admins can manage app_settings" ON public.app_settings
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)))
    WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Internal staff can read app_settings" ON public.app_settings
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('app_settings');
END
$rls$;
COMMIT;

-- ── public.audit_log ─────────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('audit_log', 'Admins/Managers read audit_log',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    NULL);
  ALTER POLICY "Admins/Managers read audit_log" ON public.audit_log
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('audit_log');
END
$rls$;
COMMIT;

-- ── public.bg_settlements ────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('bg_settlements', 'Internal staff can read settlements',
    $o$public.is_internal_staff(auth.uid())$o$,
    NULL);
  ALTER POLICY "Internal staff can read settlements" ON public.bg_settlements
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('bg_settlements');
END
$rls$;
COMMIT;

-- ── public.blocked_login_attempts ────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('blocked_login_attempts', 'Admins can manage blocked login attempts',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('blocked_login_attempts', 'Agents can insert own blocked attempts',
    NULL,
    $o$(user_id = auth.uid())$o$);
  PERFORM pg_temp.rls_initplan_guard('blocked_login_attempts', 'Managers can manage blocked login attempts',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can manage blocked login attempts" ON public.blocked_login_attempts
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Agents can insert own blocked attempts" ON public.blocked_login_attempts
    WITH CHECK ((user_id = (SELECT auth.uid())));
  ALTER POLICY "Managers can manage blocked login attempts" ON public.blocked_login_attempts
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('blocked_login_attempts');
END
$rls$;
COMMIT;

-- ── public.call_logs ─────────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('call_logs', 'Admins can manage all call logs',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('call_logs', 'Agents can insert own call logs',
    NULL,
    $o$(agent_id = auth.uid())$o$);
  PERFORM pg_temp.rls_initplan_guard('call_logs', 'Internal staff can view call logs',
    $o$public.is_internal_staff(auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('call_logs', 'Managers can manage call logs',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can manage all call logs" ON public.call_logs
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Agents can insert own call logs" ON public.call_logs
    WITH CHECK ((agent_id = (SELECT auth.uid())));
  ALTER POLICY "Internal staff can view call logs" ON public.call_logs
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))));
  ALTER POLICY "Managers can manage call logs" ON public.call_logs
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('call_logs');
END
$rls$;
COMMIT;

-- ── public.call_quality ──────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('call_quality', 'Admins read call quality',
    $o$(EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role = 'admin'::public.app_role))))$o$,
    NULL);
  ALTER POLICY "Admins read call quality" ON public.call_quality
    USING ((EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = (SELECT auth.uid())) AND (ur.role = 'admin'::public.app_role)))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('call_quality');
END
$rls$;
COMMIT;

-- ── public.call_scripts ──────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('call_scripts', 'Admins can manage call scripts',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('call_scripts', 'Internal staff can view call scripts',
    $o$public.is_internal_staff(auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('call_scripts', 'Managers can manage call scripts',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can manage call scripts" ON public.call_scripts
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Internal staff can view call scripts" ON public.call_scripts
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))));
  ALTER POLICY "Managers can manage call scripts" ON public.call_scripts
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('call_scripts');
END
$rls$;
COMMIT;

-- ── public.courier_offices ───────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('courier_offices', 'Admins/Managers manage courier offices',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    $o$public.is_admin_or_manager(auth.uid())$o$);
  PERFORM pg_temp.rls_initplan_guard('courier_offices', 'Internal staff can read courier offices',
    $o$public.is_internal_staff(auth.uid())$o$,
    NULL);
  ALTER POLICY "Admins/Managers manage courier offices" ON public.courier_offices
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))))
    WITH CHECK ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
  ALTER POLICY "Internal staff can read courier offices" ON public.courier_offices
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('courier_offices');
END
$rls$;
COMMIT;

-- ── public.courier_rates ─────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('courier_rates', 'Admins manage courier rates',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$);
  PERFORM pg_temp.rls_initplan_guard('courier_rates', 'Internal staff can read courier rates',
    $o$public.is_internal_staff(auth.uid())$o$,
    NULL);
  ALTER POLICY "Admins manage courier rates" ON public.courier_rates
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)))
    WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Internal staff can read courier rates" ON public.courier_rates
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('courier_rates');
END
$rls$;
COMMIT;

-- ── public.customer_profiles ─────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('customer_profiles', 'Internal staff can insert customer profiles',
    NULL,
    $o$public.is_internal_staff(auth.uid())$o$);
  PERFORM pg_temp.rls_initplan_guard('customer_profiles', 'Internal staff can update customer profiles',
    $o$public.is_internal_staff(auth.uid())$o$,
    $o$public.is_internal_staff(auth.uid())$o$);
  PERFORM pg_temp.rls_initplan_guard('customer_profiles', 'Internal staff can view customer profiles',
    $o$public.is_internal_staff(auth.uid())$o$,
    NULL);
  ALTER POLICY "Internal staff can insert customer profiles" ON public.customer_profiles
    WITH CHECK ((SELECT public.is_internal_staff((SELECT auth.uid()))));
  ALTER POLICY "Internal staff can update customer profiles" ON public.customer_profiles
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))))
    WITH CHECK ((SELECT public.is_internal_staff((SELECT auth.uid()))));
  ALTER POLICY "Internal staff can view customer profiles" ON public.customer_profiles
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('customer_profiles');
END
$rls$;
COMMIT;

-- ── public.financial_visibility ──────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('financial_visibility', 'Admins and managers view financial_visibility',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    NULL);
  ALTER POLICY "Admins and managers view financial_visibility" ON public.financial_visibility
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('financial_visibility');
END
$rls$;
COMMIT;

-- ── public.inbound_leads ─────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('inbound_leads', 'Admins can manage inbound leads',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('inbound_leads', 'Managers can manage inbound leads',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can manage inbound leads" ON public.inbound_leads
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Managers can manage inbound leads" ON public.inbound_leads
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('inbound_leads');
END
$rls$;
COMMIT;

-- ── public.inventory_logs ────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('inventory_logs', 'Admins can manage inventory logs',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('inventory_logs', 'Admins managers and warehouse can view inventory logs',
    $o$(public.has_role(auth.uid(), 'admin'::public.app_role) OR public.has_role(auth.uid(), 'manager'::public.app_role) OR public.has_role(auth.uid(), 'warehouse'::public.app_role))$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('inventory_logs', 'Managers can manage inventory logs',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can manage inventory logs" ON public.inventory_logs
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Admins managers and warehouse can view inventory logs" ON public.inventory_logs
    USING (((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'warehouse'::public.app_role))));
  ALTER POLICY "Managers can manage inventory logs" ON public.inventory_logs
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('inventory_logs');
END
$rls$;
COMMIT;

-- ── public.lead_distribution_config ──────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('lead_distribution_config', 'Admins and managers view lead_distribution_config',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('lead_distribution_config', 'Admins can manage lead_distribution_config',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('lead_distribution_config', 'Managers can manage lead_distribution_config',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins and managers view lead_distribution_config" ON public.lead_distribution_config
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
  ALTER POLICY "Admins can manage lead_distribution_config" ON public.lead_distribution_config
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Managers can manage lead_distribution_config" ON public.lead_distribution_config
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('lead_distribution_config');
END
$rls$;
COMMIT;

-- ── public.mex_cities ────────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('mex_cities', 'Internal staff can read mex cities',
    $o$public.is_internal_staff(auth.uid())$o$,
    NULL);
  ALTER POLICY "Internal staff can read mex cities" ON public.mex_cities
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('mex_cities');
END
$rls$;
COMMIT;

-- ── public.mex_city_aliases ──────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('mex_city_aliases', 'Internal staff can read mex city aliases',
    $o$public.is_internal_staff(auth.uid())$o$,
    NULL);
  ALTER POLICY "Internal staff can read mex city aliases" ON public.mex_city_aliases
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('mex_city_aliases');
END
$rls$;
COMMIT;

-- ── public.mex_sync_runs ─────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('mex_sync_runs', 'mex_sync_runs_select',
    $o$(public.has_role(auth.uid(), 'admin'::public.app_role) OR public.has_role(auth.uid(), 'manager'::public.app_role))$o$,
    NULL);
  ALTER POLICY "mex_sync_runs_select" ON public.mex_sync_runs
    USING (((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('mex_sync_runs');
END
$rls$;
COMMIT;

-- ── public.missed_calls ──────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('missed_calls', 'Admins/managers read all missed calls',
    $o$(EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role = ANY (ARRAY['admin'::public.app_role, 'manager'::public.app_role])))))$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('missed_calls', 'Agents read assigned missed calls',
    $o$(assigned_agent_id = auth.uid())$o$,
    NULL);
  ALTER POLICY "Admins/managers read all missed calls" ON public.missed_calls
    USING ((EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = (SELECT auth.uid())) AND (ur.role = ANY (ARRAY['admin'::public.app_role, 'manager'::public.app_role]))))));
  ALTER POLICY "Agents read assigned missed calls" ON public.missed_calls
    USING ((assigned_agent_id = (SELECT auth.uid())));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('missed_calls');
END
$rls$;
COMMIT;

-- ── public.mk_settlements ────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('mk_settlements', 'Internal staff can read mk settlements',
    $o$public.is_internal_staff(auth.uid())$o$,
    NULL);
  ALTER POLICY "Internal staff can read mk settlements" ON public.mk_settlements
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('mk_settlements');
END
$rls$;
COMMIT;

-- ── public.mk_streets ────────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('mk_streets', 'Internal staff can read mk streets',
    $o$public.is_internal_staff(auth.uid())$o$,
    NULL);
  ALTER POLICY "Internal staff can read mk streets" ON public.mk_streets
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('mk_streets');
END
$rls$;
COMMIT;

-- ── public.module_settings ───────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('module_settings', 'Admins can view module_settings',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('module_settings', 'Managers can view module_settings',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can view module_settings" ON public.module_settings
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Managers can view module_settings" ON public.module_settings
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('module_settings');
END
$rls$;
COMMIT;

-- ── public.no_parcel_rule_items ──────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('no_parcel_rule_items', 'no_parcel_rule_items_owners',
    $o$public.is_business_owner(auth.uid())$o$,
    NULL);
  ALTER POLICY "no_parcel_rule_items_owners" ON public.no_parcel_rule_items
    USING ((SELECT public.is_business_owner((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('no_parcel_rule_items');
END
$rls$;
COMMIT;

-- ── public.no_parcel_rule_runs ───────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('no_parcel_rule_runs', 'no_parcel_rule_runs_owners',
    $o$public.is_business_owner(auth.uid())$o$,
    NULL);
  ALTER POLICY "no_parcel_rule_runs_owners" ON public.no_parcel_rule_runs
    USING ((SELECT public.is_business_owner((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('no_parcel_rule_runs');
END
$rls$;
COMMIT;

-- ── public.notifications ─────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('notifications', 'Admins can manage all notifications',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('notifications', 'Managers can manage all notifications',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('notifications', 'Users can insert own notifications',
    NULL,
    $o$((user_id = auth.uid()) OR public.has_role(auth.uid(), 'admin'::public.app_role) OR public.has_role(auth.uid(), 'manager'::public.app_role))$o$);
  PERFORM pg_temp.rls_initplan_guard('notifications', 'Users can update own notifications',
    $o$(user_id = auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('notifications', 'Users can view own notifications',
    $o$(user_id = auth.uid())$o$,
    NULL);
  ALTER POLICY "Admins can manage all notifications" ON public.notifications
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Managers can manage all notifications" ON public.notifications
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
  ALTER POLICY "Users can insert own notifications" ON public.notifications
    WITH CHECK (((user_id = (SELECT auth.uid())) OR (SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role))));
  ALTER POLICY "Users can update own notifications" ON public.notifications
    USING ((user_id = (SELECT auth.uid())));
  ALTER POLICY "Users can view own notifications" ON public.notifications
    USING ((user_id = (SELECT auth.uid())));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('notifications');
END
$rls$;
COMMIT;

-- ── public.offers ────────────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('offers', 'Admins and managers manage offers',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('offers', 'Affiliates read active offers',
    $o$(is_active AND (public.get_my_affiliate_id() IS NOT NULL))$o$,
    NULL);
  ALTER POLICY "Admins and managers manage offers" ON public.offers
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
  ALTER POLICY "Affiliates read active offers" ON public.offers
    USING ((is_active AND ((SELECT public.get_my_affiliate_id()) IS NOT NULL)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('offers');
END
$rls$;
COMMIT;

-- ── public.order_history ─────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('order_history', 'Admins can manage order history',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('order_history', 'Agents can insert order history',
    NULL,
    $o$(EXISTS ( SELECT 1
   FROM public.orders
  WHERE ((orders.id = order_history.order_id) AND (orders.assigned_agent_id = auth.uid()))))$o$);
  PERFORM pg_temp.rls_initplan_guard('order_history', 'Agents can view own order history',
    $o$(EXISTS ( SELECT 1
   FROM public.orders
  WHERE ((orders.id = order_history.order_id) AND (orders.assigned_agent_id = auth.uid()))))$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('order_history', 'Managers can manage order history',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can manage order history" ON public.order_history
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Agents can insert order history" ON public.order_history
    WITH CHECK ((EXISTS ( SELECT 1
   FROM public.orders
  WHERE ((orders.id = order_history.order_id) AND (orders.assigned_agent_id = (SELECT auth.uid()))))));
  ALTER POLICY "Agents can view own order history" ON public.order_history
    USING ((EXISTS ( SELECT 1
   FROM public.orders
  WHERE ((orders.id = order_history.order_id) AND (orders.assigned_agent_id = (SELECT auth.uid()))))));
  ALTER POLICY "Managers can manage order history" ON public.order_history
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('order_history');
END
$rls$;
COMMIT;

-- ── public.order_locks ───────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('order_locks', 'Admins can manage order locks',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('order_locks', 'Internal staff can view order locks',
    $o$public.is_internal_staff(auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('order_locks', 'Managers can manage order locks',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('order_locks', 'Users can delete own locks',
    $o$(locked_by = auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('order_locks', 'Users can insert own locks',
    NULL,
    $o$(locked_by = auth.uid())$o$);
  ALTER POLICY "Admins can manage order locks" ON public.order_locks
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Internal staff can view order locks" ON public.order_locks
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))));
  ALTER POLICY "Managers can manage order locks" ON public.order_locks
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
  ALTER POLICY "Users can delete own locks" ON public.order_locks
    USING ((locked_by = (SELECT auth.uid())));
  ALTER POLICY "Users can insert own locks" ON public.order_locks
    WITH CHECK ((locked_by = (SELECT auth.uid())));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('order_locks');
END
$rls$;
COMMIT;

-- ── public.order_notes ───────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('order_notes', 'Admins can manage notes',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('order_notes', 'Agents can add notes on assigned orders',
    NULL,
    $o$(EXISTS ( SELECT 1
   FROM public.orders
  WHERE ((orders.id = order_notes.order_id) AND (orders.assigned_agent_id = auth.uid()))))$o$);
  PERFORM pg_temp.rls_initplan_guard('order_notes', 'Agents can view notes on assigned orders',
    $o$(EXISTS ( SELECT 1
   FROM public.orders
  WHERE ((orders.id = order_notes.order_id) AND (orders.assigned_agent_id = auth.uid()))))$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('order_notes', 'Managers can manage notes',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can manage notes" ON public.order_notes
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Agents can add notes on assigned orders" ON public.order_notes
    WITH CHECK ((EXISTS ( SELECT 1
   FROM public.orders
  WHERE ((orders.id = order_notes.order_id) AND (orders.assigned_agent_id = (SELECT auth.uid()))))));
  ALTER POLICY "Agents can view notes on assigned orders" ON public.order_notes
    USING ((EXISTS ( SELECT 1
   FROM public.orders
  WHERE ((orders.id = order_notes.order_id) AND (orders.assigned_agent_id = (SELECT auth.uid()))))));
  ALTER POLICY "Managers can manage notes" ON public.order_notes
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('order_notes');
END
$rls$;
COMMIT;

-- ── public.pbx_health_snapshots ──────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('pbx_health_snapshots', 'Admins read pbx health',
    $o$(EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role = 'admin'::public.app_role))))$o$,
    NULL);
  ALTER POLICY "Admins read pbx health" ON public.pbx_health_snapshots
    USING ((EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = (SELECT auth.uid())) AND (ur.role = 'admin'::public.app_role)))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('pbx_health_snapshots');
END
$rls$;
COMMIT;

-- ── public.personal_list_holds ───────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('personal_list_holds', 'Admins can delete holds',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('personal_list_holds', 'Agents can insert own holds',
    NULL,
    $o$(public.is_internal_staff(auth.uid()) AND (agent_id = auth.uid()))$o$);
  PERFORM pg_temp.rls_initplan_guard('personal_list_holds', 'Agents can update own holds',
    $o$(public.is_internal_staff(auth.uid()) AND ((agent_id = auth.uid()) OR public.is_admin_or_manager(auth.uid())))$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('personal_list_holds', 'Internal staff can read active holds',
    $o$(public.is_internal_staff(auth.uid()) AND ((status = 'active'::text) OR (agent_id = auth.uid()) OR public.is_admin_or_manager(auth.uid())))$o$,
    NULL);
  ALTER POLICY "Admins can delete holds" ON public.personal_list_holds
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
  ALTER POLICY "Agents can insert own holds" ON public.personal_list_holds
    WITH CHECK (((SELECT public.is_internal_staff((SELECT auth.uid()))) AND (agent_id = (SELECT auth.uid()))));
  ALTER POLICY "Agents can update own holds" ON public.personal_list_holds
    USING (((SELECT public.is_internal_staff((SELECT auth.uid()))) AND ((agent_id = (SELECT auth.uid())) OR (SELECT public.is_admin_or_manager((SELECT auth.uid()))))));
  ALTER POLICY "Internal staff can read active holds" ON public.personal_list_holds
    USING (((SELECT public.is_internal_staff((SELECT auth.uid()))) AND ((status = 'active'::text) OR (agent_id = (SELECT auth.uid())) OR (SELECT public.is_admin_or_manager((SELECT auth.uid()))))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('personal_list_holds');
END
$rls$;
COMMIT;

-- ── public.prediction_lead_items ─────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('prediction_lead_items', 'Admins can manage prediction lead items',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('prediction_lead_items', 'Agents can manage items for assigned leads',
    $o$(EXISTS ( SELECT 1
   FROM public.prediction_leads
  WHERE ((prediction_leads.id = prediction_lead_items.lead_id) AND (prediction_leads.assigned_agent_id = auth.uid()))))$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('prediction_lead_items', 'Managers can manage prediction lead items',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can manage prediction lead items" ON public.prediction_lead_items
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Agents can manage items for assigned leads" ON public.prediction_lead_items
    USING ((EXISTS ( SELECT 1
   FROM public.prediction_leads
  WHERE ((prediction_leads.id = prediction_lead_items.lead_id) AND (prediction_leads.assigned_agent_id = (SELECT auth.uid()))))));
  ALTER POLICY "Managers can manage prediction lead items" ON public.prediction_lead_items
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('prediction_lead_items');
END
$rls$;
COMMIT;

-- ── public.prediction_leads ──────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('prediction_leads', 'Admins can manage prediction leads',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('prediction_leads', 'Agents can update assigned leads',
    $o$(assigned_agent_id = auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('prediction_leads', 'Agents can view assigned leads',
    $o$(assigned_agent_id = auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('prediction_leads', 'Managers can manage prediction leads',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can manage prediction leads" ON public.prediction_leads
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Agents can update assigned leads" ON public.prediction_leads
    USING ((assigned_agent_id = (SELECT auth.uid())));
  ALTER POLICY "Agents can view assigned leads" ON public.prediction_leads
    USING ((assigned_agent_id = (SELECT auth.uid())));
  ALTER POLICY "Managers can manage prediction leads" ON public.prediction_leads
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('prediction_leads');
END
$rls$;
COMMIT;

-- ── public.prediction_lists ──────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('prediction_lists', 'Admins can manage prediction lists',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('prediction_lists', 'Internal staff can view prediction lists',
    $o$public.is_internal_staff(auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('prediction_lists', 'Managers can manage prediction lists',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can manage prediction lists" ON public.prediction_lists
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Internal staff can view prediction lists" ON public.prediction_lists
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))));
  ALTER POLICY "Managers can manage prediction lists" ON public.prediction_lists
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('prediction_lists');
END
$rls$;
COMMIT;

-- ── public.prediction_segment_lists ──────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('prediction_segment_lists', 'Admins/Managers manage segment lists',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    $o$public.is_admin_or_manager(auth.uid())$o$);
  PERFORM pg_temp.rls_initplan_guard('prediction_segment_lists', 'Internal staff can view segment lists',
    $o$public.is_internal_staff(auth.uid())$o$,
    NULL);
  ALTER POLICY "Admins/Managers manage segment lists" ON public.prediction_segment_lists
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))))
    WITH CHECK ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
  ALTER POLICY "Internal staff can view segment lists" ON public.prediction_segment_lists
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('prediction_segment_lists');
END
$rls$;
COMMIT;

-- ── public.prediction_segment_members ────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('prediction_segment_members', 'Admins/Managers manage members',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    $o$public.is_admin_or_manager(auth.uid())$o$);
  PERFORM pg_temp.rls_initplan_guard('prediction_segment_members', 'Agents see assigned members',
    $o$((assigned_agent_id = auth.uid()) OR public.is_admin_or_manager(auth.uid()))$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('prediction_segment_members', 'Agents update own assignments',
    $o$(assigned_agent_id = auth.uid())$o$,
    $o$(assigned_agent_id = auth.uid())$o$);
  ALTER POLICY "Admins/Managers manage members" ON public.prediction_segment_members
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))))
    WITH CHECK ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
  ALTER POLICY "Agents see assigned members" ON public.prediction_segment_members
    USING (((assigned_agent_id = (SELECT auth.uid())) OR (SELECT public.is_admin_or_manager((SELECT auth.uid())))));
  ALTER POLICY "Agents update own assignments" ON public.prediction_segment_members
    USING ((assigned_agent_id = (SELECT auth.uid())))
    WITH CHECK ((assigned_agent_id = (SELECT auth.uid())));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('prediction_segment_members');
END
$rls$;
COMMIT;

-- ── public.products ──────────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('products', 'Admins can manage products',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('products', 'Internal staff can view products',
    $o$public.is_internal_staff(auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('products', 'Managers can manage products',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can manage products" ON public.products
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Internal staff can view products" ON public.products
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))));
  ALTER POLICY "Managers can manage products" ON public.products
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('products');
END
$rls$;
COMMIT;

-- ── public.profiles ──────────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('profiles', 'Admins can delete profiles',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('profiles', 'Admins can update any profile',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('profiles', 'Managers can delete profiles',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('profiles', 'Managers can update profiles',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('profiles', 'Managers can view all profiles',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('profiles', 'Users can insert own profile',
    NULL,
    $o$(user_id = auth.uid())$o$);
  PERFORM pg_temp.rls_initplan_guard('profiles', 'Users can update own profile',
    $o$(user_id = auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('profiles', 'Users can view own profile',
    $o$((user_id = auth.uid()) OR public.has_role(auth.uid(), 'admin'::public.app_role))$o$,
    NULL);
  ALTER POLICY "Admins can delete profiles" ON public.profiles
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Admins can update any profile" ON public.profiles
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Managers can delete profiles" ON public.profiles
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
  ALTER POLICY "Managers can update profiles" ON public.profiles
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
  ALTER POLICY "Managers can view all profiles" ON public.profiles
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
  ALTER POLICY "Users can insert own profile" ON public.profiles
    WITH CHECK ((user_id = (SELECT auth.uid())));
  ALTER POLICY "Users can update own profile" ON public.profiles
    USING ((user_id = (SELECT auth.uid())));
  ALTER POLICY "Users can view own profile" ON public.profiles
    USING (((user_id = (SELECT auth.uid())) OR (SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('profiles');
END
$rls$;
COMMIT;

-- ── public.role_permissions ──────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('role_permissions', 'Admins can view role_permissions',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('role_permissions', 'Managers can view role_permissions',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can view role_permissions" ON public.role_permissions
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Managers can view role_permissions" ON public.role_permissions
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('role_permissions');
END
$rls$;
COMMIT;

-- ── public.role_privacy ──────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('role_privacy', 'Admins and managers view role_privacy',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    NULL);
  ALTER POLICY "Admins and managers view role_privacy" ON public.role_privacy
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('role_privacy');
END
$rls$;
COMMIT;

-- ── public.segment_engine_config ─────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('segment_engine_config', 'Admins manage segment_engine_config',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    $o$public.is_admin_or_manager(auth.uid())$o$);
  PERFORM pg_temp.rls_initplan_guard('segment_engine_config', 'Internal staff can read segment_engine_config',
    $o$public.is_internal_staff(auth.uid())$o$,
    NULL);
  ALTER POLICY "Admins manage segment_engine_config" ON public.segment_engine_config
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))))
    WITH CHECK ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
  ALTER POLICY "Internal staff can read segment_engine_config" ON public.segment_engine_config
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('segment_engine_config');
END
$rls$;
COMMIT;

-- ── public.shift_assignments ─────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('shift_assignments', 'Admins can manage shift assignments',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('shift_assignments', 'Agents can view own assignments',
    $o$(user_id = auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('shift_assignments', 'Managers can manage shift assignments',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can manage shift assignments" ON public.shift_assignments
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Agents can view own assignments" ON public.shift_assignments
    USING ((user_id = (SELECT auth.uid())));
  ALTER POLICY "Managers can manage shift assignments" ON public.shift_assignments
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('shift_assignments');
END
$rls$;
COMMIT;

-- ── public.shift_breaks ──────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('shift_breaks', 'Admins manage all breaks',
    $o$public.is_admin_or_manager(auth.uid())$o$,
    $o$public.is_admin_or_manager(auth.uid())$o$);
  PERFORM pg_temp.rls_initplan_guard('shift_breaks', 'Agents insert own breaks',
    NULL,
    $o$(user_id = auth.uid())$o$);
  PERFORM pg_temp.rls_initplan_guard('shift_breaks', 'Agents update own breaks',
    $o$(user_id = auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('shift_breaks', 'Agents view own breaks',
    $o$((user_id = auth.uid()) OR public.is_admin_or_manager(auth.uid()))$o$,
    NULL);
  ALTER POLICY "Admins manage all breaks" ON public.shift_breaks
    USING ((SELECT public.is_admin_or_manager((SELECT auth.uid()))))
    WITH CHECK ((SELECT public.is_admin_or_manager((SELECT auth.uid()))));
  ALTER POLICY "Agents insert own breaks" ON public.shift_breaks
    WITH CHECK ((user_id = (SELECT auth.uid())));
  ALTER POLICY "Agents update own breaks" ON public.shift_breaks
    USING ((user_id = (SELECT auth.uid())));
  ALTER POLICY "Agents view own breaks" ON public.shift_breaks
    USING (((user_id = (SELECT auth.uid())) OR (SELECT public.is_admin_or_manager((SELECT auth.uid())))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('shift_breaks');
END
$rls$;
COMMIT;

-- ── public.shift_login_logs ──────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('shift_login_logs', 'Admins can manage shift login logs',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('shift_login_logs', 'Agents can insert own shift login logs',
    NULL,
    $o$(user_id = auth.uid())$o$);
  PERFORM pg_temp.rls_initplan_guard('shift_login_logs', 'Agents can update own shift login logs',
    $o$(user_id = auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('shift_login_logs', 'Agents can view own shift login logs',
    $o$(user_id = auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('shift_login_logs', 'Managers can manage shift login logs',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can manage shift login logs" ON public.shift_login_logs
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Agents can insert own shift login logs" ON public.shift_login_logs
    WITH CHECK ((user_id = (SELECT auth.uid())));
  ALTER POLICY "Agents can update own shift login logs" ON public.shift_login_logs
    USING ((user_id = (SELECT auth.uid())));
  ALTER POLICY "Agents can view own shift login logs" ON public.shift_login_logs
    USING ((user_id = (SELECT auth.uid())));
  ALTER POLICY "Managers can manage shift login logs" ON public.shift_login_logs
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('shift_login_logs');
END
$rls$;
COMMIT;

-- ── public.shift_templates ───────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('shift_templates', 'Admins can manage shift templates',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('shift_templates', 'Internal staff can view shift templates',
    $o$public.is_internal_staff(auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('shift_templates', 'Managers can manage shift templates',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can manage shift templates" ON public.shift_templates
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Internal staff can view shift templates" ON public.shift_templates
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))));
  ALTER POLICY "Managers can manage shift templates" ON public.shift_templates
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('shift_templates');
END
$rls$;
COMMIT;

-- ── public.shifts ────────────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('shifts', 'Admins can manage shifts',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('shifts', 'Agents can view their assigned shifts',
    $o$(EXISTS ( SELECT 1
   FROM public.shift_assignments sa
  WHERE ((sa.shift_id = shifts.id) AND (sa.user_id = auth.uid()))))$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('shifts', 'Managers can manage shifts',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can manage shifts" ON public.shifts
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Agents can view their assigned shifts" ON public.shifts
    USING ((EXISTS ( SELECT 1
   FROM public.shift_assignments sa
  WHERE ((sa.shift_id = shifts.id) AND (sa.user_id = (SELECT auth.uid()))))));
  ALTER POLICY "Managers can manage shifts" ON public.shifts
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('shifts');
END
$rls$;
COMMIT;

-- ── public.suppliers ─────────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('suppliers', 'Admins can manage suppliers',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('suppliers', 'Internal staff can view suppliers',
    $o$public.is_internal_staff(auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('suppliers', 'Managers can manage suppliers',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can manage suppliers" ON public.suppliers
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Internal staff can view suppliers" ON public.suppliers
    USING ((SELECT public.is_internal_staff((SELECT auth.uid()))));
  ALTER POLICY "Managers can manage suppliers" ON public.suppliers
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('suppliers');
END
$rls$;
COMMIT;

-- ── public.telephony_extensions ──────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('telephony_extensions', 'Admins manage telephony_extensions',
    $o$(EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role = 'admin'::public.app_role))))$o$,
    $o$(EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role = 'admin'::public.app_role))))$o$);
  PERFORM pg_temp.rls_initplan_guard('telephony_extensions', 'Users read own telephony row',
    $o$(user_id = auth.uid())$o$,
    NULL);
  ALTER POLICY "Admins manage telephony_extensions" ON public.telephony_extensions
    USING ((EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = (SELECT auth.uid())) AND (ur.role = 'admin'::public.app_role)))))
    WITH CHECK ((EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = (SELECT auth.uid())) AND (ur.role = 'admin'::public.app_role)))));
  ALTER POLICY "Users read own telephony row" ON public.telephony_extensions
    USING ((user_id = (SELECT auth.uid())));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('telephony_extensions');
END
$rls$;
COMMIT;

-- ── public.user_roles ────────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('user_roles', 'Admins can manage roles',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('user_roles', 'Managers can view roles',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('user_roles', 'Users can view own role',
    $o$((user_id = auth.uid()) OR public.has_role(auth.uid(), 'admin'::public.app_role))$o$,
    NULL);
  ALTER POLICY "Admins can manage roles" ON public.user_roles
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Managers can view roles" ON public.user_roles
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
  ALTER POLICY "Users can view own role" ON public.user_roles
    USING (((user_id = (SELECT auth.uid())) OR (SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role))));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('user_roles');
END
$rls$;
COMMIT;

-- ── public.user_warehouse ────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('user_warehouse', 'Admins can manage user warehouse',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('user_warehouse', 'Managers can manage user warehouse',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('user_warehouse', 'Users can view own warehouse items',
    $o$(user_id = auth.uid())$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('user_warehouse', 'Warehouse users can manage all warehouse items',
    $o$public.has_role(auth.uid(), 'warehouse'::public.app_role)$o$,
    $o$public.has_role(auth.uid(), 'warehouse'::public.app_role)$o$);
  ALTER POLICY "Admins can manage user warehouse" ON public.user_warehouse
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Managers can manage user warehouse" ON public.user_warehouse
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
  ALTER POLICY "Users can view own warehouse items" ON public.user_warehouse
    USING ((user_id = (SELECT auth.uid())));
  ALTER POLICY "Warehouse users can manage all warehouse items" ON public.user_warehouse
    USING ((SELECT public.has_role((SELECT auth.uid()), 'warehouse'::public.app_role)))
    WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'warehouse'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('user_warehouse');
END
$rls$;
COMMIT;

-- ── public.webhooks ──────────────────────────────────────────────────────────────
BEGIN;
SET LOCAL lock_timeout = '5s';
DO $rls$
BEGIN
  PERFORM pg_temp.rls_initplan_guard('webhooks', 'Admins can manage webhooks',
    $o$public.has_role(auth.uid(), 'admin'::public.app_role)$o$,
    NULL);
  PERFORM pg_temp.rls_initplan_guard('webhooks', 'Managers can manage webhooks',
    $o$public.has_role(auth.uid(), 'manager'::public.app_role)$o$,
    NULL);
  ALTER POLICY "Admins can manage webhooks" ON public.webhooks
    USING ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)));
  ALTER POLICY "Managers can manage webhooks" ON public.webhooks
    USING ((SELECT public.has_role((SELECT auth.uid()), 'manager'::public.app_role)));
EXCEPTION WHEN lock_not_available THEN
  PERFORM pg_temp.rls_initplan_busy('webhooks');
END
$rls$;
COMMIT;

-- ── done ────────────────────────────────────────────────────────────────────
BEGIN;
NOTIFY pgrst, 'reload schema';
COMMIT;

DO $done$
DECLARE
  busy text := pg_catalog.btrim(COALESCE(pg_catalog.current_setting('elyon.rls_initplan_busy', true), ''));
BEGIN
  IF busy <> '' THEN
    RAISE EXCEPTION 'rls_initplan: lock timeout on: % - every other table is done; run the same apply command again', busy;
  END IF;
END
$done$;
